data: " "
train_data: "/home/corn/PycharmProjects/fingerprint/train"
test_data: "/home/corn/PycharmProjects/fingerprint/test"

project: runs/resnet18_wo_maxpool_16384_fingerprint_aug_2  # project name
name: linear_egis  # experiment name

transform: egis
batch_size: 128
num_workers: 8
model: "resnet18_wo_maxpool"
weights: "runs/resnet18_wo_maxpool_16384_fingerprint_aug_2/checkpoint.pth"
extract_layers: [ 'layer1', 'layer2', 'layer3' ]
device: 1
exist_ok: True

distance: "linear"
classifier_weights: "runs/resnet18_wo_maxpool_16384_fingerprint_aug_2/linear_egis/best_acc.pth"